### ISSUE TITLE
upgrade to xcode 7

### ISSUE THREAD

**Issue by entaq** [entaq/Cliq#14]

**Comment by jberkey78** [comment]
Should I upgrade to 7?

**Comment by entaq** [comment]
Yeah - do it!

**Comment by jberkey78** [comment]
sweet, gotta update my phone to 9 as well :)

On Thu, Sep 24, 2015 at 1:55 PM, Arun Nagarajan notifications@github.com
wrote:

> Yeah - do it!
> 
> On Thu, Sep 24, 2015 at 5:29 AM jberkey78 notifications@github.com
> wrote:
> 
> > Should I upgrade to 7?
> > 
> > Sent from my iPhone
> > 
> > > On Sep 24, 2015, at 12:32 AM, Arun Nagarajan <notifications@github.com
> > 
> > wrote:
> > 
> > > Closed #14 via 4ce6a0f.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/entaq/Cliq/issues/14#issuecomment-142867409.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/entaq/Cliq/issues/14#issuecomment-143004356.

## 

Jonathan Berkey
