### ISSUE TITLE
Clicking on a cliq goes to cliq photos

### ISSUE THREAD

**Issue by entaq** [entaq/Cliq#2]
This is a new collection view controller that shows the list of photos in a cliq. Each photo gets one cell and the creator of the photo is the in the bottom right.

This vc needs a cliqId to exist. This is passed in from the HomeVC when a cliq is selected or a after a cliq is created. When it will only the photos originally uploaded.

**Comment by aenhsaihan** [comment]
Will it always be the same facebook creator for these photos? So, in other words, will it always show the same facebook user in the bottom right in these photos?

**Comment by jberkey78** [comment]
when I try to run a build of the Master it fails, I am guessing you ran
into the same issue?

On Sat, Sep 12, 2015 at 11:54 PM, Anar Enhsaihan notifications@github.com
wrote:

> Closed #2 https://github.com/entaq/Cliq/issues/2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/entaq/Cliq/issues/2#event-407975465.

## 

Jonathan Berkey

**Comment by jberkey78** [comment]
I am guessing this is the cause?

[image: Inline image 1]

On Sat, Sep 12, 2015 at 11:54 PM, Anar Enhsaihan notifications@github.com
wrote:

> Closed #2 https://github.com/entaq/Cliq/issues/2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/entaq/Cliq/issues/2#event-407975465.

## 

Jonathan Berkey
